create Categories
devOnlineStore/frontend pull request #15
Opened 2023-08-26 11:20 UTC by darktend

## Ticket
Link to ticket: https://teamchallengeonlinestore.atlassian.net/jira/software/projects/TOS/boards/1?assignee=609eb5f09b362f0069a70820&selectedIssue=TOS-95

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*
Added pictures to the project created a category component
- Change 1
- Change 2

## Screenshots
![image](https://github.com/devOnlineStore/frontend/assets/65015457/12a92722-421b-4a9b-94eb-39adc4852631)

(prefer animated gif)

## Checklist
- [x] Did you test it?
- [x] Did you add a screenshot?
- [x] Did you fix the merge conflict?
- [x] Did you fill the PR template?
- [x] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [x ] Did you share the link in a group chat?

2023-08-27 08:23 UTC, KarlAnna commented
The cards look different from the design

2023-08-27 10:28 UTC, dev1B commented
Could you provide screenshot for mobile?

2023-08-27 10:29 UTC, dev1B commented
What kind of changes did you make?

2023-08-27 10:30 UTC, dev1B commented
The screenshot contains a bug, could you fix it?

2023-08-27 10:30 UTC, dev1B requested changes
Requested changes

2023-08-27 11:04 UTC, dev1B commented
<img width="498" alt="image" src="https://github.com/devOnlineStore/frontend/assets/15249473/d6e3e5e2-d04d-49cc-8f20-f5edb1fc97bc">
Please, review the checklist

2023-08-27 11:41 UTC, darktend commented
@dev1B @KarlAnna review please

2023-08-29 12:03 UTC, dev1B requested changes

2023-08-29 12:03 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +.head {
`categoriesList/container/wrapper` could be better

2023-08-29 12:03 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +.link {
This is not a link

2023-08-29 12:03 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +    a {
better to create class, please

2023-08-29 12:03 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +@media (max-width: 980px) {
we don't have desktop version

2023-08-29 12:03 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.tsx
> +import { categories } from '@/utils/data';
In this component better to use props instead of import

2023-09-03 12:11 UTC, dev1B requested changes

2023-09-03 12:11 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +.categoryList {
CategoriesList

2023-09-03 12:11 UTC, dev1B commented on app/components/CategoriesList/CategoriesList.module.scss
> +    border-bottom-left-radius: 10px;
/* top-left | top-right | bottom-right | bottom-left */
border-radius: 1px 2px 3px 4px;

2023-09-03 16:13 UTC, merged