Create component badge
devOnlineStore/frontend pull request #19
Opened 2023-08-29 17:22 UTC by darktend

## Ticket
Link to ticket:https://teamchallengeonlinestore.atlassian.net/jira/software/projects/TOS/boards/1?assignee=609eb5f09b362f0069a70820&selectedIssue=TOS-119

## Description

I created a badge, created a custom component for discounts, for new products and for marking whether the product is in stock

## Screenshots
![image](https://github.com/devOnlineStore/frontend/assets/65015457/21747c8a-d184-4d3b-bb03-832729d2e798)

(prefer animated gif)

## Checklist
- [ ] Did you test it?
- [ ] Did you add a screenshot?
- [ ] Did you fix the merge conflict?
- [ ] Did you fill the PR template?
- [ ] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-09-03 11:45 UTC, dev1B requested changes

2023-09-03 11:45 UTC, dev1B commented on app/components/Badge/Badge.tsx
> +    type?: 'default' | 'discount' | 'arrivals' | 'stock';
Does "Out of stock" mean "stock"?

2023-09-03 11:45 UTC, dev1B commented on app/components/Badge/Badge.module.scss
> +        max-width: 141px;
Do we need this line?

2023-09-03 11:45 UTC, dev1B commented on app/components/Badge/Badge.module.scss
> +        height: 22px;
Why did you add fixed sizes?

2023-09-03 11:45 UTC, dev1B commented on app/components/Badge/Badge.module.scss
> +        border-radius: 100px;
Why did you add 100px?

2023-09-03 11:46 UTC, dev1B commented on app/components/Badge/Badge.module.scss
> +        font-family: 'Montserrat', sans-serif;
Could you start using scss variables?

2023-09-06 17:53 UTC, darktend commented on app/components/Badge/Badge.module.scss
> +        max-width: 141px;
add pading

2023-09-06 17:55 UTC, darktend commented on app/components/Badge/Badge.tsx
> +    type?: 'default' | 'discount' | 'arrivals' | 'stock';
rename type

2023-09-11 16:37 UTC, dev1B commented on .eslintrc
> +//    "plugin:@typescript-eslint/recommended-type-checked",
What do you plan to do with this?

2023-09-11 16:37 UTC, dev1B commented on app/components/Badge/Badge.tsx
> +  type?: 'essentials' | 'deals' | 'newbies' | 'inventory';
@Taraskin777 @KarlAnna Do you like these types? Are these clear to you?

2023-09-11 16:37 UTC, dev1B commented on .eslintrc
> +//    "plugin:@typescript-eslint/recommended-type-checked",
@Taraskin777 @KarlAnna Can we remove these?

2023-09-13 16:41 UTC, Taraskin777 commented on app/components/Badge/Badge.tsx
> +  type?: 'essentials' | 'deals' | 'newbies' | 'inventory';
as for me, not exactly

2023-09-13 16:49 UTC, Taraskin777 commented on .eslintrc
> +//    "plugin:@typescript-eslint/recommended-type-checked",
it's hard for me to say if this is necessary for our project because I haven't used these rules before

2023-09-15 07:20 UTC, darktend commented on .eslintrc
> +//    "plugin:@typescript-eslint/recommended-type-checked",
@dev1B

2023-09-15 08:42 UTC, dev1B approved these changes

2023-09-15 08:45 UTC, merged