add footer and update favicon + metadata of website
devOnlineStore/frontend pull request #2
Opened 2023-07-28 14:03 UTC by KarlAnna

2023-07-28 15:19 UTC, dev1B requested changes
Can u add a screenshot of the work 
Also, I would like to recommend you isolate styles based on component

2023-07-28 20:04 UTC, dev1B commented
example: https://itnext.io/structuring-your-sass-projects-c8d41fa55ed4

2023-07-31 11:56 UTC, KarlAnna commented
![pr-footer](https://github.com/devOnlineStore/frontend/assets/106392024/a03bc607-b2b6-4561-93e6-2e45a95525ed)

2023-07-31 12:05 UTC, dev1B commented on components/Header/Header.tsx
> -import './header.scss';
You should include styles in[ _app](https://nextjs.org/docs/pages/building-your-application/styling/css-modules)

2023-08-02 08:09 UTC, dev1B commented on components/Header/Header.tsx
> -import './header.scss';
Should be `import './header.scss';` 
I think "_" does not work in js.

2023-08-02 08:11 UTC, dev1B commented on next.config.js
> -    includePaths: [path.join(__dirname, 'styles')]
@KarlAnna SCSS folder name, u dont use sass 


https://sass-lang.com/guide/

<img width="498" alt="image" src="https://github.com/devOnlineStore/frontend/assets/15249473/7f0582c1-6ea0-4b56-a608-839641250a19">
<img width="393" alt="image" src="https://github.com/devOnlineStore/frontend/assets/15249473/93c83b45-1eea-4285-9490-ce34c0b8de53">

2023-08-02 08:12 UTC, dev1B commented on sass/abstracts/_variables.scss
> +$secondary-font-family: 'Yeseva One';
Could you add default font, please

2023-08-02 08:12 UTC, dev1B commented on sass/base/_typography.scss
> +  // font-weight: 400;
comment

2023-08-02 08:13 UTC, dev1B requested changes
Could you fix comments, please

2023-08-02 08:14 UTC, dev1B commented on components/Header/_header.scss
> +@import '/sass/abstracts/variables';
@import '/scss/abstracts/variables';

2023-08-02 08:14 UTC, dev1B commented on components/Footer/Footer.tsx
> +import './_footer.scss';
`import './footer.scss';`

2023-08-02 08:31 UTC, KarlAnna commented on sass/abstracts/_variables.scss
> +$secondary-font-family: 'Yeseva One';
What do you mean by that?

2023-08-02 09:39 UTC, dev1B approved these changes

2023-08-02 10:06 UTC, merged