fix width and gaps for outlined buttons
devOnlineStore/frontend pull request #21
Opened 2023-09-02 15:03 UTC by Taraskin777

## Ticket
Link to ticket:
https://teamchallengeonlinestore.atlassian.net/jira/software/projects/TOS/boards/1?assignee=712020%3A4102cab5-ba41-4622-b0e9-fca65c2e84c6&selectedIssue=TOS-116

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*

fix width and gaps for outlined buttons

- Change 1
- Change 2

## Screenshots

https://prnt.sc/XckvABwZ3jg2

## Checklist
- [ ] Did you test it?
- [ ] Did you add a screenshot?
- [ ] Did you fix the merge conflict?
- [ ] Did you fill the PR template?
- [ ] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-09-03 11:49 UTC, dev1B requested changes

2023-09-03 11:49 UTC, dev1B commented on app/components/Button/Button.module.scss
> +  padding: 0px 10px 0px 4px;
Why did you add this? Could you tell for which purpose?

2023-09-03 11:49 UTC, dev1B commented on app/modules/auth/SignInModal/SignInModal.tsx
> +              // disabled
Why did u remove it?

2023-09-04 11:31 UTC, Taraskin777 commented on app/modules/auth/SignInModal/SignInModal.tsx
> +              // disabled
Because I don't see disabled buttons in Figma:
https://www.figma.com/file/8w03QojCyA361zdg7E8sBS/Team-challenge----Online-store?node-id=3284%3A10250&mode=dev

2023-09-04 11:31 UTC, Taraskin777 commented on app/components/Button/Button.module.scss
> +  padding: 0px 10px 0px 4px;
I add this according to the Figma's design:
https://www.figma.com/file/8w03QojCyA361zdg7E8sBS/Team-challenge----Online-store?node-id=3280%3A10490&mode=dev
But now I've seen that other instances of outlined buttons don't have padding. But, if I remove this line, elements in the button look worse)

2023-09-11 15:12 UTC, dev1B approved these changes

2023-09-11 15:13 UTC, merged