TOS-96-Add Popular Products section
devOnlineStore/frontend pull request #22
Opened 2023-09-03 10:36 UTC by KarlAnna

## Ticket
Link to ticket: https://teamchallengeonlinestore.atlassian.net/browse/TOS-96

## Description
Added Popular Products section and components for product list and product card

- Add PopularProducts component
- Add ProductsList component
- Add Card component
- Change onClick prop interface for Button and IconBtn

## Screenshots

https://www.loom.com/share/b40850e89db64257b0557d3bd4f10ab8?sid=d168914b-d3d2-44c9-b5d7-396ec6c30de0

## Checklist
- [X] Did you test it?
- [X] Did you add a screenshot?
- [X] Did you fix the merge conflict?
- [X] Did you fill the PR template?
- [ ] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-09-03 11:15 UTC, dev1B requested changes

2023-09-03 11:15 UTC, dev1B commented on app/components/ProductsList/ProductsList.tsx
> +            <ul className={styles.cardList}>
Do you really need this list?

2023-09-03 11:15 UTC, dev1B commented on app/components/Card/Card.tsx
> +                        filled ? <RiStarSFill key={index} className={styles.filledStar} /> : <RiStarSLine key={index} className={styles.star} />
Do you expect 3.3, 4.2 (float value) rating?

2023-09-03 11:15 UTC, dev1B commented on app/components/Card/Card.tsx
> +        e.preventDefault();
Why did you add this?

2023-09-03 11:15 UTC, dev1B commented on app/components/Card/Card.tsx
> +        e.preventDefault();
Why did you add `e.preventDefault()`?

2023-09-03 11:38 UTC, darktend commented on app/components/Card/Card.tsx
> +                <IconBtn onClick={handleFavorite} Icon={isFavorite ? RiHeartFill : RiHeartLine} iconClassName={cn(styles.heart, { [styles.activeHeart]: isFavorite })} type='rounded' />
maybe it's better ({cn(styles.heart, { [styles.activeHeart]: isFavorite })})}) to put it behind the return?

2023-09-04 10:07 UTC, KarlAnna commented on app/components/ProductsList/ProductsList.tsx
> +            <ul className={styles.cardList}>
Do you mean component or tag <ul>?
If it's a tag, why shouldn't it be here? It's a list of products

2023-09-04 10:28 UTC, dev1B commented on app/components/Card/Card.tsx
> +                <IconBtn onClick={handleFavorite} Icon={isFavorite ? RiHeartFill : RiHeartLine} iconClassName={cn(styles.heart, { [styles.activeHeart]: isFavorite })} type='rounded' />
You can use it as const 

const favoriteIcon = useMemo( () => 
<IconBtn onClick={handleFavorite} Icon={isFavorite ? RiHeartFill : RiHeartLine} iconClassName={cn(styles.heart, { [styles.activeHeart]: isFavorite })} type='rounded' />

, [deps])

2023-09-04 17:25 UTC, merged