Create FAQ page
devOnlineStore/frontend pull request #24
Opened 2023-09-09 17:49 UTC by Taraskin777

## Ticket
Link to ticket:

https://teamchallengeonlinestore.atlassian.net/jira/software/projects/TOS/boards/1?assignee=712020%3A4102cab5-ba41-4622-b0e9-fca65c2e84c6&selectedIssue=TOS-150

## Description
Create FAQ page according to Figma's design

- Change 1
- Change 2

## Screenshots

![Screenshot_7](https://github.com/devOnlineStore/frontend/assets/94867301/6c90b96f-bf47-4769-84e1-c5dbf22a8f33)
![Screenshot_8](https://github.com/devOnlineStore/frontend/assets/94867301/3b4b3152-2e81-4cd7-a726-6e3c6323301b)

## Checklist
- [ ] Did you test it?
- [ ] Did you add a screenshot?
- [ ] Did you fix the merge conflict?
- [ ] Did you fill the PR template?
- [ ] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-09-09 17:56 UTC, dev1B requested changes
<img width="1679" alt="image" src="https://github.com/devOnlineStore/frontend/assets/15249473/c0ac9e73-d446-4809-a0bd-3d4668c202c0">
Looks like you forgot complete it for desktop

2023-09-11 14:17 UTC, Taraskin777 commented
> <img alt="image" width="1679" src="https://user-images.githubusercontent.com/15249473/266795727-c0ac9e73-d446-4809-a0bd-3d4668c202c0.png"> Looks like you forgot complete it for desktop

fixed

2023-09-11 15:26 UTC, dev1B requested changes

2023-09-11 15:26 UTC, dev1B commented on app/components/BurgerMenu/BurgerMenu.tsx
> +            <Link href="/faq">FAQ</Link>
👍

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/Accordion.tsx
> +  FaqList: FaqItem[];
camelcase, please

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/Accordion.tsx
> +const Accordion = ({ FaqList }: FaqListProps) => {
Could you move this component into the components folder and make it more generic ( types should not refer to FAQ)

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/AccordionItem.tsx
> +const AccordionItem = ({ faqItem, onClick, isOpen }: AccItem) => {
Could you move this component into the components folder and make it more generic ( types should not refer to FAQ)

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/AccordionItem.tsx
> +interface FaqItem {
This type is duplicated.

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/Faq.tsx
> +      <p className={styles.title}>Тут ви знайдете відповіді на найпоширеніші запитання </p>
subtitle mb?

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/Faq.module.scss
> +@media (width >= 768px) {
Could you create scss const for media/mixin

2023-09-11 15:26 UTC, dev1B commented on app/components/Faq/Faq.module.scss
> +  & p {
Could you use class?

2023-09-14 19:47 UTC, dev1B commented on app/components/Faq/Accordion.tsx
> +    <ul>
ul?

2023-09-17 13:58 UTC, Taraskin777 commented on app/components/Faq/Accordion.tsx
> +  FaqList: FaqItem[];
+

2023-09-17 13:58 UTC, Taraskin777 commented on app/components/Faq/Accordion.tsx
> +  FaqList: FaqItem[];
+

2023-09-17 13:58 UTC, Taraskin777 commented on app/components/Faq/Accordion.tsx
> +const Accordion = ({ FaqList }: FaqListProps) => {
+

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/AccordionItem.tsx
> +const AccordionItem = ({ faqItem, onClick, isOpen }: AccItem) => {
fixed

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/AccordionItem.tsx
> +interface FaqItem {
fixed

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/Faq.tsx
> +      <p className={styles.title}>Тут ви знайдете відповіді на найпоширеніші запитання </p>
fixed

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/Faq.module.scss
> +
fixed

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/Faq.module.scss
> +@media (width >= 768px) {
fixed

2023-09-17 13:59 UTC, Taraskin777 commented on app/components/Faq/Faq.module.scss
> +  & p {
no

2023-09-17 14:00 UTC, Taraskin777 commented on app/components/Faq/AccordionItem.tsx
> +      <button className={questionClass} onClick={() => onClick()} type="button">
id doesn't work

2023-09-17 14:00 UTC, Taraskin777 commented on app/components/Faq/Accordion.tsx
> +    <ul>
ul

2023-09-18 23:13 UTC, merged