TOS-182-Add product page
devOnlineStore/frontend pull request #31
Opened 2023-09-27 11:36 UTC by KarlAnna

## Ticket
Link to ticket: https://teamchallengeonlinestore.atlassian.net/browse/TOS-182

## Description
*Please provide a small summary of your changes and how they resolved the issues in the ticket:*
Added a product page and created several components for it. Improved the basic slider

[//]: # ( - Added decoreted prop for Button to add underlining to some buttons)

[//]: # ( - Fixed Card styles according to design)

[//]: # ( - Added FavoriteIcon component for the icon that adds to favourites)

[//]: # ( - Added base Dropdown and HeightBasedDropdown components)

[//]: # ( - Added ProductDetails component for displaying all info about a product)

[//]: # ( - Added ProductSliders component for sliders on mobile/table versions page)

[//]: # ( - Updated ProductsList component. Added touch scrolling prop and fix styles)

[//]: # ( - Updated PromoSlider component according to updated Slider component)

[//]: # ( - Added reviews and containerClassName props for Rating component)

[//]: # ( - Added RecommendedProducts component with the section of recommended products)

[//]: # ( - Added Reviews component with the section of reviews to products)

## Screenshots

[mobile](https://www.loom.com/share/9e91cda1bfc24517b981e1f5a9a33f60?sid=8b334fc4-bd56-433a-aa9a-350c22c20606)
[table](https://www.loom.com/share/af7a5a26d71f441693f1cb45e4b5fd7a?sid=e43a900a-54ff-4fab-80fb-0ae3f14a93fc)
[desktop](https://www.loom.com/share/9d3eadf146a64d69b9546b419f277a2d?sid=368bdbb9-4e54-4140-8d1a-5e8881141e92)

## Checklist
- [X] Did you test it?
- [X] Did you add a screenshot?
- [X] Did you fix the merge conflict?
- [ ] Did you fill the PR template?
- [X] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-09-27 19:38 UTC, dev1B requested changes

2023-09-27 19:38 UTC, dev1B commented on app/components/Button/Button.tsx
> +  decoreted?: boolean;
Not sure if it good idea to add this. I think it could be completed by using the classname. 
This is not a common feature for buttons.

2023-09-27 19:38 UTC, dev1B commented on app/components/Card/Card.tsx
> +const Card = ({ id, img, title, rating, reviews, price }: CardProps) => {
Maybe `ProductCard`

2023-09-27 19:38 UTC, dev1B commented on app/components/Card/Card.tsx
> +        style={{ width: '100%', height: 'auto', borderRadius: '10px', overflow: 'hidden' }}
Could we use classname?

2023-09-27 19:38 UTC, dev1B commented on app/components/Dropdown/Dropdown.tsx
Dropdown name is so common. Could you be more specific about the name of this component?


You have harcoded value (https://github.com/devOnlineStore/frontend/pull/31/files#diff-dafe7ff6aabd4ced3397c3e449df21789a060617e3c95634ae5f1179e191c858R47)

2023-09-27 19:38 UTC, dev1B commented on app/components/FavoriteIcon/FavoriteIcon.tsx
> +const FavoriteIcon = ({ isFavorite, onClick }: FavoriteIconProps) => {
Could you check `React.memo`

https://www.linkedin.com/pulse/reactmemo-vs-usememo-kristiyan-velkov/

2023-09-27 19:38 UTC, dev1B commented on app/components/HeightBasedDropdown/HeightBasedDropdown.tsx
> +        onSelect={(height) => setSelectedHeight(Number(height))}
Could you use `useCallback`, please

2023-09-27 19:38 UTC, dev1B commented on app/components/HeightBasedDropdown/HeightBasedDropdown.tsx
> +  const selectedPrice =
`useMemo`?

2023-09-27 19:38 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.module.scss
> +    & .leftContent {
Could you use better naming

2023-09-27 19:38 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.tsx
> +};
Could you move into `data` folder. We would like to reuse it later.

2023-09-27 19:38 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.tsx
> +            <div className={styles.leftContent}>
Maybe `gallery` will be better than `leftContent`

2023-09-27 19:38 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.tsx
> +          <div className={styles.rightContent}>
`.productDetails` or `.details`

2023-09-27 19:38 UTC, dev1B commented on app/components/ProductSliders/ProductSliders.tsx
> +        onSwiper={(swiper) => setThumbsSwiper(swiper)}
Cau you use 
`onSwiper={setThumbsSwiper}`

2023-09-27 19:38 UTC, dev1B commented on app/components/Rating/Rating.tsx
> +  containerClassName?: string;
just `className`

2023-09-27 19:38 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +const windowWidth = window.innerWidth;
If I am not mistake this should not change during resize

2023-09-27 19:38 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +const windowWidth = window.innerWidth;
Maybe you would like to create custom hook-like device detect, use "resize" event, and our breakpoints

https://usehooks-ts.com/react-hook/use-window-size

2023-09-27 19:38 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +    {windowWidth < 768 ? <Title text="Відгуки" /> : <Title align="center" text="Відгуки" />}
hardcoded window size :(

2023-09-27 19:38 UTC, dev1B commented on app/components/Slider/Slider.tsx
>  const Slider = ({
We returned back :D ( put everything inside the component )
Rename this component, please.

2023-09-27 19:38 UTC, dev1B commented on app/components/Slider/Slider.tsx
> +  sliderClassName?: string;
mb `className`

2023-09-27 19:38 UTC, dev1B commented on app/products/[productId]/page.tsx
> +    <Header />
Could you try `layout.tsx`
https://nextjs.org/docs/pages/building-your-application/routing/pages-and-layouts

2023-09-27 19:38 UTC, dev1B commented on scss/utils/_responsive.scss
> +@mixin max-w-laptop {
This naming is confusing :(
mb `laptop-and-below` / `laptop-below`

2023-09-27 19:53 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +    {windowWidth < 768 ? <Title text="Відгуки" /> : <Title align="center" text="Відгуки" />}
https://www.developerway.com/posts/reconciliation-in-react

2023-09-29 08:24 UTC, KarlAnna commented on app/products/[productId]/page.tsx
> +    <Header />
Then it displays 404 error page

2023-09-30 09:55 UTC, dev1B requested changes

2023-09-30 09:55 UTC, dev1B commented on app/components/ProductCard/ProductCard.tsx
> +        className={cn(styles.img, className)}
Do you need `className` here?

2023-09-30 09:55 UTC, dev1B commented on app/components/Button/Button.tsx
> +  className?: string;
Dont need this, because we already have `className?: string;` in `ButtonHTMLAttributes<HTMLButtonElement>`

2023-09-30 09:55 UTC, dev1B commented on app/components/Dropdown/Dropdown.tsx
> +  optionUnit?: string;
Instead of this, I would suggest you map your options to add unit there

2023-09-30 09:55 UTC, dev1B commented on app/components/Dropdown/Dropdown.tsx
> +  options: string[] | number[];
options - should be like `{label, value}`
Could you check react-select(https://www.npmjs.com/package/react-select)?

2023-09-30 09:55 UTC, dev1B commented on app/components/ProductCard/ProductCard.tsx
> +        className={cn(styles.img, className)}
I can not find where you use it

2023-09-30 09:55 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.tsx
> +  const windowWidth = window.innerWidth;
useDev?

2023-09-30 13:03 UTC, KarlAnna commented on app/components/ProductDetails/ProductDetails.tsx
> +  const windowWidth = window.innerWidth;
We agreed that Dima would do the hook. Then I'll fix it

2023-09-30 13:08 UTC, KarlAnna commented on app/components/ProductCard/ProductCard.tsx
> +        className={cn(styles.img, className)}
Idk why I put it here. I put it away

2023-09-30 13:28 UTC, dev1B commented on app/products/[productId]/page.tsx
> +    <Header />
We have FAQ with layout
https://github.com/devOnlineStore/frontend/blob/dev/app/faq/layout.tsx

2023-10-03 07:01 UTC, dev1B requested changes

2023-10-03 07:01 UTC, dev1B commented on app/components/ProductDetails/ProductDetails.tsx
> +      </p>
Also, could you replace the name of class. 

Example of use: 
```
...
<Breadcrumbs routes={[ 'Каталог', category, subcategory,  <span>{title}</span>]}/>
...
```

2023-10-03 07:07 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +    )}
I guess, it should be done on the title component side. Because it is common to our design

2023-10-03 07:07 UTC, dev1B commented on app/components/Reviews/Reviews.tsx
> +    )}
Maybe it will be better to use media query (scss)

2023-10-04 06:38 UTC, KarlAnna commented on app/components/ProductDetails/ProductDetails.tsx
> +import Layout from '@/app/products/[productId]/layout';
What exactly? Layout?

2023-10-05 12:33 UTC, dev1B approved these changes

2023-10-05 12:33 UTC, dev1B commented on app/components/Slider/Slider.tsx
> +  loop,
Why do you skip `loop` property ?
https://github.com/devOnlineStore/frontend/pull/31/files#diff-0460503f090deec56cb79bdcd126b51becc3aecc1384c2e6e0e49d38de7981b0R54

2023-10-05 12:33 UTC, dev1B commented on app/components/PromoSlider/PromoSlider.tsx
> +  OverlayContent: generateOverlayContent(image),
camel case

2023-10-06 06:39 UTC, merged