TOS-205: Create Page Catalog
devOnlineStore/frontend pull request #32
Opened 2023-09-27 17:19 UTC by denvudd

## Ticket
Link to ticket: https://teamchallengeonlinestore.atlassian.net/browse/TOS-205

## Description
Create filter menu (mobile and desktop) for subcategory catalog

## Screenshots
<details>
  <summary>Spoiler</summary>
  <img src="https://github.com/devOnlineStore/frontend/assets/68691654/0abf6c36-7991-4725-aa40-32dfdac37010"></img>
</details>
<details>
  <summary>Spoiler</summary>
  <img src="https://github.com/devOnlineStore/frontend/assets/68691654/8abb3f4e-ef77-4a90-86ed-98626e851f2a"></img>
</details>
<details>
  <summary>Spoiler</summary>
  <img src="https://github.com/devOnlineStore/frontend/assets/68691654/15825f97-c96e-4fda-a2ee-5f2e1fe3ab9a"></img>
</details>
<details>
  <summary>Spoiler</summary>
  <img src="https://github.com/devOnlineStore/frontend/assets/68691654/f9cb2d6f-b8b0-4505-a733-54b25013195a"></img>
</details>

(prefer animated gif)

## Checklist
- [X] Did you test it?
- [X] Did you add a screenshot?
- [X] Did you fix the merge conflict?
- [X] Did you fill the PR template?
- [X] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [X] Did you share the link in a group chat?

2023-09-27 18:56 UTC, dev1B requested changes

2023-09-27 18:56 UTC, dev1B commented on public/assets/icons/filter.svg
Did you check `react-icons`?

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.module.scss
> +.button {
I think we have these buttons.

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +  const pathname = `/categories/${params.slug}/${params.subcategorySlug}`;
`params.categorySlug`
Could you fix it, please

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.module.scss
> +.button {
https://github.com/devOnlineStore/frontend/blob/dev/app/components/Button/Button.module.scss#L89

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.module.scss
> +.burgerBtn {
I think we we have burgerBtn

@KarlAnna

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const onCheckboxesChange = (query: qs.ParsedQuery<string>) => {
onFilter(s)Change

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +            value="text"
This part is not clear for me.

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +                featured: currentParams.featured !== 'true' ? 'true' : null,
not clear for me
Could you explain?

Better to avoid `!` 
`currentParams.featured === 'true' ? false : true`

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const toggleMenu = (active: boolean) => {
Could you use `useMemo/useCallback`, please

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +                onClick={() => {
![image](https://github.com/devOnlineStore/frontend/assets/15249473/87e5af44-2e8e-4f89-88ab-d577b1173987)
`useMemo/useCallback`

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +  const searchParamsArray = Object.keys(searchParams);
Maybe `filtersNames`

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +            href={{
I am not sure if we want to have redirects here

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +              value="text"
This line is not clear

2023-09-27 18:56 UTC, dev1B commented on app/components/Catalog/CatalogPanel/CatalogPanel.tsx
> +  results: number;
I think we should find better name for this prop

2023-09-28 06:25 UTC, denvudd commented on app/categories/[slug]/[subcategorySlug]/page.tsx
> +          searchParams={searchParams}
Don't you like the names of these params or how they function or are passed?

2023-09-28 06:25 UTC, denvudd commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.module.scss
> +.button {
Yes, you're right. I just using Link styled as buttons instead of actual buttons. I used this approach to modify query params "on the server." Is this a bad practice or in this case is acceptable?

I have an idea to create buttonVariants in the button component, similar to what's done in the UI library shad-cn (though it's not based on Tailwind):
https://github.com/denvudd/djinni-clone-frontend.github.io/blob/d2ccb760e1a768aa44805809b8c7edbbd95dc710/src/components/ui/Button.tsx#L7

2023-09-28 06:26 UTC, denvudd commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +  const pathname = `/categories/${params.slug}/${params.subcategorySlug}`;
Do I need to change the slug param or just the name of this prop?

2023-09-28 06:31 UTC, denvudd commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.module.scss
> +.burgerBtn {
That's correct. The component used for the mobile burger menu is designed exclusively for the mobile menu, and this is a slightly different use case. Do I need to redesign the BurgerMenu component for this? Perhaps, it's possible to create a component similar to Sheet:
https://ui.shadcn.com/docs/components/sheet

2023-09-28 06:31 UTC, denvudd commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +                featured: currentParams.featured !== 'true' ? 'true' : null,
Here, I'm passing a query parameter to the `onCheckboxChange` function (after fixing `onFilterChange`). I'm passing the current parsed query parameters (now I realize I may not need to do this, as they are already spread within the function). I'm checking if "`featured`" is not present in the current parameters, in which case I need to add "true" (as a string because the `onFilterChange `function accepts an argument of type `qs.ParsedQuery<string>`, and this argument will be used later in the `stringifyUrl` function from the `query-string` library). If such a parameter already exists, it needs to be removed by setting it to null (because of `{ skipNull: true }` in `stringifyUrl`).

I will fix the onChange as follows:
...
```ts
onChange={() =>
  onFilterChange({
    featured: currentParams.featured === 'true' ? null : 'true',
  })
}
```
...

2023-09-28 06:40 UTC, denvudd commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +            href={{
As far as I understand, this part of the filter is like navigation that should switch subcategories. Since the `CatalogFilterSidebar` is a server-side component, I change the subcategory using a Link. Are there any better ways to do this?

2023-09-28 06:40 UTC, denvudd commented on app/components/Catalog/CatalogPanel/CatalogPanel.tsx
> +  results: number;
Maybe just a `productsCount`?

2023-09-28 06:41 UTC, denvudd commented on app/components/Checkbox/Checkbox.tsx
> +  onChange?: () => void;
I'm not sure if this makes sense. For example, here's the callback type definition in Radix UI:
![image](https://github.com/devOnlineStore/frontend/assets/68691654/e3e6a33f-a592-463b-b828-6f13b0eac4fe)
What do you think?

2023-09-28 06:42 UTC, denvudd commented on app/components/Catalog/SortButton/SortButton.tsx
> +        control: () => styles.select,
This is how classNames are typed in react-select. Unfortunately, react-select styling is quite specific

![image](https://github.com/devOnlineStore/frontend/assets/68691654/a4d8860a-fccd-45f2-ab8e-6845c90d86b9)

2023-09-28 07:48 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +  const pathname = `/categories/${params.slug}/${params.subcategorySlug}`;
...
- categories
- [categorySlug]
   - [subcategorySlug]

....

2023-09-28 07:53 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +                featured: currentParams.featured !== 'true' ? 'true' : null,
onFilterChange => fieldName => (checked) => {

// featured: currentParams.featured === 'true' ? null : 'true',
{...currentParams, 
[fieldName]: checked,
}


onFilterChange(Enum.fieldName (// featured))

2023-09-30 09:35 UTC, dev1B requested changes

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/filter-params.ts
> +export enum SortBy {
Could you check https://www.typescriptlang.org/docs/handbook/enums.html

It should be like `
enum Direction {
  Up = "up",
  Down = "down",
  ...
}

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +                href={{
Why don't you use  href= {`/${categorySlug}/${subcategory.slug}`}
Do you have any reason for that ?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +                [FilterBy.featured]: featured ? undefined : 'true',
Do you really need `featured ? undefined : 'true',`? 

Could we try to use `[FilterBy.featured]: featured`

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +        onClick={() => toggleMenu(true)}
`useMemo/useCallback` :)

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +            onChange={() => onFilterChange(FilterBy.featured)(true)}
onChange={handleFilterChange(FilterBy.featured)}
onChange={handleFilterChange(FilterBy.instock)}
onChange={handleFilterChange(FilterBy.preorder)}

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +            checked={currentParams.instock === 'true'}
Could you remove `=== 'true'` part, please

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const onFilterChange = React.useCallback(
Could you move this function to parent?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/SortButton/SortButton.tsx
> +  const handleSelect = React.useCallback(
Could you move this function to parent?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const onClearFilters = React.useCallback(() => {
Could you move this function to parent?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +        filtersNames.map((filterName) => (
`filtersNames?.map(...)

2023-09-30 09:35 UTC, dev1B commented on app/(categories)/[categorySlug]/[subcategorySlug]/page.tsx
> +  [FilterBy.instock]: 'true';
I don't like it :)

2023-09-30 09:35 UTC, dev1B commented on app/(categories)/[categorySlug]/[subcategorySlug]/page.tsx
> +  [FilterBy.instock]: 'true';
Could you read https://bobbyhadz.com/blog/typescript-enum-as-restricted-key-or-value-type

2023-09-30 09:35 UTC, dev1B commented on app/(categories)/[categorySlug]/[subcategorySlug]/page.tsx
> +export interface CatalogParams {
If it is common, then could you create types folder inside `(categories)` ?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +    () => Object.keys(searchParams).map((key) => FilterBy[key as keyof typeof FilterBy]),
Object.keys(searchParams).map((key`:FilterBy`)
Could you try this one?

2023-09-30 09:35 UTC, dev1B commented on app/components/Catalog/SortButton/SortButton.tsx
> +  const setDefaultValue = React.useCallback(() => {
It should be `useMemo`

2023-10-02 12:44 UTC, denvudd commented on app/(categories)/[categorySlug]/[subcategorySlug]/page.tsx
> +  [FilterBy.instock]: 'true';
Do you mean something like that?

``` typescript
type FilterByKeys = {
  [key in keyof typeof FilterBy]: (typeof FilterBy)[key];
};

export interface CatalogSearchParams extends FilterByKeys {
  sortBy: SortBy;
}
```

2023-10-02 12:45 UTC, denvudd commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const onFilterChange = React.useCallback(
What do you mean to parent?

2023-10-02 12:49 UTC, denvudd commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +            onChange={() => onFilterChange(FilterBy.featured)(true)}
Will this be a problem if there are other filters with values that are not `boolean`? If it will be a number etc.? Maybe it's better like this?:
```typescript
function (fieldName, value) {
 [fieldName]: value
}
```

2023-10-02 12:50 UTC, denvudd commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +        onClick={() => toggleMenu(true)}
Do you mean toggleMenu function? It's already using useCallback or it's something wrong with him
![image](https://github.com/devOnlineStore/frontend/assets/68691654/181514e3-c64b-49d0-81b6-929a9295467c)

2023-10-02 13:07 UTC, denvudd commented on app/components/Catalog/CatalogFilterSidebar/CatalogFilterSidebar.tsx
> +                [FilterBy.featured]: featured ? undefined : 'true',
I didn't understand this. The logic here is as follows: if this parameter exists, then undefined (remove the filter), if it doesn't exist, then set the parameter to 'true'. If you use instock/preorder/featured, it will use the value of the current parameter (from searchParams). If it doesn't exist, nothing will happen, if it exists nothing will happen either. Also, we can't pass a boolean to query param because it will be just "&instock=false". Is there something that I missing?

2023-10-02 13:11 UTC, denvudd commented on app/components/Catalog/CatalogFilterLabels/CatalogFilterLabels.tsx
> +    () => Object.keys(searchParams).map((key) => FilterBy[key as keyof typeof FilterBy]),
For some reason `.keys()` returns only `string[]` without any typing, so `.map()` iterates the string array and gives an error if `key: FilterBy`. I can do something like this maybe?:
```typescript
const filtersNames = React.useMemo(() => {
    const filters = Object.keys(searchParams) as FilterBy[];

    return filters.map((key) => key);
  }, [searchParams]);
```
  
[stackoverflow](https://stackoverflow.com/questions/52856496/typescript-object-keys-return-string)

2023-10-03 07:10 UTC, dev1B commented on app/components/Catalog/filter-params.ts
> +export enum SortBy {
yes, could you follow the existing pattern for all enums, please

2023-10-05 13:05 UTC, dev1B commented on app/(categories)/[categorySlug]/[subcategorySlug]/page.tsx
> +export interface CatalogParams {
not fixed

2023-10-05 13:16 UTC, dev1B requested changes

2023-10-05 13:16 UTC, dev1B commented on app/components/Catalog/Catalog.tsx
> +  );
This code requires refactoring.

2023-10-05 13:16 UTC, dev1B commented on app/components/Catalog/Catalog.tsx
> +  );
(duplication)

2023-10-05 13:16 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  onFilter: (fieldName: FilterBy) => (value: React.ChangeEvent<HTMLInputElement>) => void;
dev, [5 Oct 2023, 16:00:37]:
onFilterChange: (filters) => {}

я б так залишив +-

перент не мав б знати про твої

onFilter: (fieldName: FilterBy) => (value: React.ChangeEvent<HTMLInputElement>) => void;

махінації такі)

тобто

ти робиш в поточному компоненті

handleFilterChange(fieldName) {
 return (value) => ({
...restParams
 [fieldName]: value
})
}

2023-10-13 13:02 UTC, dev1B requested changes

2023-10-13 13:02 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  }, [isActive, setIsActive]);
I think you forget to add `router` into deps

2023-10-13 13:02 UTC, dev1B commented on app/components/Catalog/CatalogFilterMobile/CatalogFilterMobile.tsx
> +  const filterMenu = [
useMemo

2023-11-02 15:17 UTC, merged