fix(dropdown): implement outside click hook
devOnlineStore/frontend pull request #41
Opened 2023-10-29 10:20 UTC by bessu4ka

## Ticket
Link to ticket:

## Description
Custom dropdown did not close when we clicked outside the component, this is now fixed

## Screenshots
![image](https://github.com/devOnlineStore/frontend/assets/79211699/efe64048-a7b6-450e-9349-d5f1911f8a7e)

## Checklist
- [ ] Did you test it?
- [ ] Did you add a screenshot?
- [ ] Did you fix the merge conflict?
- [ ] Did you fill the PR template?
- [ ] Did you review this PR on your own?

#### Last step if the ABOVE STEPS are COMPLETED!
- [ ] Did you share the link in a group chat?

2023-10-29 10:39 UTC, dev1B requested changes

2023-10-29 10:39 UTC, dev1B commented on app/modules/core/hooks/use-outside-click.ts
> +export const useOutsideClick = (callback: () => void) => {
Could you add the option `ref` param 
Like https://chakra-ui.com/docs/hooks/use-outside-click

2023-10-29 10:39 UTC, dev1B commented on .editorconfig
> +[*]
Could you remove this file, then add into gitignore

2023-10-29 10:39 UTC, dev1B commented on app/modules/core/hooks/use-outside-click.ts
> +      if (ref.current && !ref.current.contains(event.target as Node)) {
`!ref.current?.contains(...)`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Optional_chaining#optional_chaining_with_function_calls

2023-10-31 11:22 UTC, bessu4ka commented on app/modules/core/hooks/use-outside-click.ts
> +export const useOutsideClick = (callback: () => void) => {
hmm, do you mean getting a ref like a callback?

2023-10-31 11:23 UTC, bessu4ka commented on app/modules/core/hooks/use-outside-click.ts
> +export const useOutsideClick = (callback: () => void) => {
Sorry, I read that the ref should be optional

2023-11-02 11:58 UTC, merged